### PR TITLE
validate union

### PR DESCRIPTION
**Pull request by ekinzie**
This fixes a case where a client could cause netconfd to abort by sending it data that fails a validation test.

### CODE REVIEW

**Comment by vlvassilev** [comment]
I already committed the "unit test for invalid union value in leaf-list" patch. The "return status value from val_make_sprintf_string" patch is changing existing public API. This function should only fail due to depleted dynamic memory and I think we can live without dedicated returned error code in addition to NULL pointer. I think the "do not abort as a result of invalid data supplied by user" can be worked without changing the public API in non-backward compatible way that will require major version semver increase.

**Comment by ekinzie** [comment]
Yes, it's possible to make val_make_sprintf_string ignore errors so long as it gets a non-zero length string back from val_sprintf_simval_nc.  The public API would not change in this case and an error can still be reported to the client.  I will update the pull request with these changes if that sounds ok.

**Comment by vlvassilev** [comment]
Check this commit https://github.com/vlvassilev/yuma123/commit/d3db955704dc6a031f8d46e97b0c6bb6ddadc464 it fixes the problem at a higher level. The val_ functions should get a valid val from their callers otherwise we risk endless loops of error handling.

Great catch and testcase.

**Comment by ekinzie** [comment]
That's a vast improvement over my changes.  I think the two commits related to m__free are still valid.

**Pull request closed without merging**
